
import React, { useState } from 'react';
import { useStore } from '../context/StoreContext';
import { Equipment, OrderStatus, Client, OrderType, Address, Order } from '../types';
import { Search, ShoppingCart, Plus, Minus, Trash2, ArrowRight, UserPlus, Check, FileText, ArrowLeft, Package, DollarSign, Calendar, ChevronRight, MapPin, CreditCard, MessageCircle, Printer, Home, CheckCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { printOrder } from '../lib/printHandler';

type FlowMode = 'SELECT_MODE' | 'SELECT_PERIOD' | 'CART' | 'DETAILS' | 'SUCCESS';

const NewOrder = () => {
  const { equipment, clients, addOrder, getEquipmentStock, addClient } = useStore();
  const navigate = useNavigate();
  
  // Flow State
  const [currentStep, setCurrentStep] = useState<FlowMode>('SELECT_MODE');
  const [orderType, setOrderType] = useState<OrderType>('PEDIDO');
  const [createdOrder, setCreatedOrder] = useState<Order | null>(null);
  
  // Data State
  const [searchTerm, setSearchTerm] = useState('');
  const [cart, setCart] = useState<{item: Equipment, quantity: number}[]>([]);
  const [billingPeriod, setBillingPeriod] = useState<'DIARIA' | 'SEMANAL' | 'QUINZENAL' | 'MENSAL'>('MENSAL');
  
  // Client State
  const [selectedClient, setSelectedClient] = useState<string>('');
  const [newClientMode, setNewClientMode] = useState(false);
  
  // Form Data States
  const initialAddress: Address = {
    street: '', number: '', neighborhood: '', city: '', state: '', zipCode: '', complement: '', reference: ''
  };
  
  const [newClientData, setNewClientData] = useState<Client>({id: '', name: '', document: '', phone: '', email: '', ...initialAddress});
  const [deliveryAddress, setDeliveryAddress] = useState<Address>(initialAddress);
  
  const [shippingCost, setShippingCost] = useState(0);
  const [observations, setObservations] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<'PIX' | 'CARTAO' | 'DINHEIRO' | 'BOLETO' | 'FATURADO'>('PIX');

  // Helpers
  const addToCart = (item: Equipment) => {
    const stock = getEquipmentStock(item.id);
    if (orderType === 'PEDIDO' && stock.available <= 0) {
        alert("Sem estoque disponível para locação imediata!");
        return;
    }
    const existing = cart.find(x => x.item.id === item.id);
    if (existing) {
      if (orderType === 'PEDIDO' && existing.quantity >= stock.available) {
          alert("Quantidade máxima disponível atingida.");
          return;
      }
      setCart(cart.map(x => x.item.id === item.id ? { ...x, quantity: x.quantity + 1 } : x));
    } else {
      setCart([...cart, { item, quantity: 1 }]);
    }
  };

  const updateQuantity = (id: string, delta: number) => {
    setCart(cart.map(x => {
        if (x.item.id === id) {
            const stock = getEquipmentStock(id);
            const newQty = x.quantity + delta;
            if (orderType === 'PEDIDO' && newQty > stock.available) return x;
            return { ...x, quantity: Math.max(1, newQty) };
        }
        return x;
    }));
  };

  const removeFromCart = (id: string) => setCart(cart.filter(x => x.item.id !== id));

  const calculateTotalForPeriod = (period: 'DIARIA' | 'SEMANAL' | 'QUINZENAL' | 'MENSAL') => {
    return cart.reduce((acc, curr) => {
      let price = 0;
      switch(period) {
        case 'DIARIA': price = curr.item.priceDaily; break;
        case 'SEMANAL': price = curr.item.priceWeekly; break;
        case 'QUINZENAL': price = curr.item.priceBiWeekly; break;
        case 'MENSAL': price = curr.item.priceMonthly; break;
      }
      return acc + (price * curr.quantity);
    }, 0);
  };

  const currentTotal = calculateTotalForPeriod(billingPeriod) + shippingCost;

  const handleFinishOrder = async () => {
    let clientIdToUse = selectedClient;
    let clientName = clients.find(c => c.id === selectedClient)?.name || "Cliente";

    // Validate form
    if (newClientMode) {
        if(!newClientData.name || !newClientData.document) {
            alert("Preencha os dados do novo cliente.");
            return;
        }
        // Create client first
        try {
            const createdClient = await addClient(newClientData);
            clientIdToUse = createdClient.id;
            clientName = createdClient.name;
        } catch (e) {
            alert("Erro ao criar cliente. Tente novamente.");
            return;
        }
    } else if (!clientIdToUse) {
      alert("Selecione um cliente.");
      return;
    }

    try {
        const newOrder = await addOrder({
            id: '', // Generated by backend/store
            type: orderType,
            clientId: clientIdToUse,
            clientName,
            items: cart.map(c => ({ 
              equipmentId: c.item.id,
              equipmentName: c.item.name, 
              quantity: c.quantity,
              priceSnapshot: billingPeriod === 'MENSAL' ? c.item.priceMonthly : billingPeriod === 'QUINZENAL' ? c.item.priceBiWeekly : billingPeriod === 'SEMANAL' ? c.item.priceWeekly : c.item.priceDaily
            })),
            status: orderType === 'ORCAMENTO' ? OrderStatus.QUOTATION : OrderStatus.PENDING,
            createdAt: new Date().toISOString(),
            deliveryDate: new Date().toISOString(), 
            returnDate: new Date(Date.now() + 86400000 * 30).toISOString(),
            
            // Detailed Address
            ...deliveryAddress,
            
            shippingCost,
            totalAmount: currentTotal,
            billingPeriod,
            paymentMethod,
            observations
          });
          
          setCreatedOrder(newOrder);
          setCurrentStep('SUCCESS');
    } catch (e) {
        alert("Erro ao finalizar pedido.");
    }
  };
  
  // Address Update Helper
  const updateAddress = (field: keyof Address, value: string) => {
    setDeliveryAddress(prev => ({ ...prev, [field]: value }));
  };

  const updateNewClient = (field: keyof Client, value: string) => {
    setNewClientData(prev => ({ ...prev, [field]: value }));
  };

  const handleSendWhatsApp = () => {
      if(!createdOrder) return;
      
      const client = clients.find(c => c.id === createdOrder.clientId);
      const phone = client?.phone || newClientData.phone || '';
      const cleanPhone = phone.replace(/\D/g, '');
      
      const itemsList = createdOrder.items.map(i => `- ${i.quantity}x ${i.equipmentName || 'Item'}`).join('\n');
      
      const text = `*ORCAMENTO QUARK LOCACOES*\n\n` +
                   `Ola, ${createdOrder.clientName}!\n` +
                   `Segue o detalhamento do seu pedido:\n\n` +
                   `*ITENS:*\n${itemsList}\n\n` +
                   `*Periodo:* ${createdOrder.billingPeriod}\n` +
                   `*Frete:* R$ ${createdOrder.shippingCost.toFixed(2)}\n` +
                   `*TOTAL:* R$ ${createdOrder.totalAmount.toFixed(2)}\n\n` +
                   `Forma de Pagamento: ${createdOrder.paymentMethod}\n` +
                   `Ficamos a disposicao!`;
      
      const url = `https://wa.me/55${cleanPhone}?text=${encodeURIComponent(text)}`;
      window.open(url, '_blank');
  };

  return (
    <div className="max-w-[1200px] mx-auto pb-20">
      <div className="flex items-center justify-between mb-8 sticky top-0 bg-[#F2F2F7]/95 backdrop-blur z-20 py-4">
         <div className="flex items-center">
            {currentStep !== 'SUCCESS' && (
                <button 
                  onClick={() => {
                    if(currentStep === 'SELECT_PERIOD') setCurrentStep('SELECT_MODE');
                    else if(currentStep === 'CART' && orderType === 'PEDIDO') setCurrentStep('SELECT_PERIOD');
                    else if(currentStep === 'CART' && orderType === 'ORCAMENTO') setCurrentStep('SELECT_MODE');
                    else if(currentStep === 'DETAILS') setCurrentStep('CART');
                    else navigate(-1);
                  }}
                  className="mr-4 p-2 bg-white rounded-full shadow-sm text-gray-600 hover:text-gray-900 border border-gray-200 transition-colors"
                >
                    <ArrowLeft className="w-5 h-5" />
                </button>
            )}
            <div>
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">
                    {orderType === 'PEDIDO' ? 'Novo Pedido' : 'Novo Orçamento'}
                </h2>
                {currentStep !== 'SELECT_MODE' && currentStep !== 'SUCCESS' && (
                    <div className="flex items-center text-xs font-semibold tracking-wide uppercase text-gray-400 mt-1 space-x-2">
                        {orderType === 'PEDIDO' && <>
                            <span className={currentStep === 'SELECT_PERIOD' ? 'text-blue-600' : ''}>Período</span>
                            <ChevronRight className="w-3 h-3" />
                        </>}
                        <span className={currentStep === 'CART' ? 'text-blue-600' : ''}>Itens</span>
                        <ChevronRight className="w-3 h-3" />
                        <span className={currentStep === 'DETAILS' ? 'text-blue-600' : ''}>Dados</span>
                    </div>
                )}
            </div>
         </div>
      </div>

      {currentStep === 'SUCCESS' && createdOrder ? (
          <div className="max-w-xl mx-auto text-center pt-10 animate-scale-up">
              <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                  <CheckCircle className="w-12 h-12 text-green-600" />
              </div>
              <h2 className="text-3xl font-bold text-gray-900 mb-2">Sucesso!</h2>
              <p className="text-gray-500 mb-8">
                  {createdOrder.type === 'ORCAMENTO' ? 'Orçamento gerado com sucesso.' : 'Pedido de locação confirmado.'}
                  <br/>O número do registro é <strong>#{createdOrder.id.slice(0, 8)}</strong>
              </p>

              <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 mb-8 text-left">
                  <h3 className="font-bold text-gray-800 mb-4 border-b border-gray-100 pb-2">Resumo Rápido</h3>
                  <div className="space-y-2 text-sm text-gray-600">
                      <div className="flex justify-between"><span>Cliente:</span> <span className="font-bold text-gray-900">{createdOrder.clientName}</span></div>
                      <div className="flex justify-between"><span>Total:</span> <span className="font-bold text-gray-900">R$ {createdOrder.totalAmount.toFixed(2)}</span></div>
                      <div className="flex justify-between"><span>Itens:</span> <span className="font-bold text-gray-900">{createdOrder.items.length} itens</span></div>
                  </div>
              </div>

              <div className="space-y-3">
                  <button 
                    onClick={handleSendWhatsApp}
                    className="w-full py-4 bg-green-500 text-white rounded-xl font-bold hover:bg-green-600 transition-colors shadow-lg shadow-green-500/20 flex items-center justify-center"
                  >
                      <MessageCircle className="w-5 h-5 mr-2" /> Enviar Orçamento no WhatsApp
                  </button>
                  
                  <button 
                    onClick={() => printOrder(createdOrder, equipment)}
                    className="w-full py-4 bg-blue-50 text-blue-600 border border-blue-100 rounded-xl font-bold hover:bg-blue-100 transition-colors flex items-center justify-center"
                  >
                      <Printer className="w-5 h-5 mr-2" /> Imprimir / Baixar PDF
                  </button>

                  <button 
                    onClick={() => navigate('/orders')}
                    className="w-full py-4 bg-gray-100 text-gray-600 rounded-xl font-bold hover:bg-gray-200 transition-colors flex items-center justify-center"
                  >
                      <Home className="w-5 h-5 mr-2" /> Voltar para Pedidos
                  </button>
              </div>
          </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 space-y-6">
                {currentStep === 'SELECT_MODE' && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 py-10">
                        <button onClick={() => { setOrderType('PEDIDO'); setCurrentStep('SELECT_PERIOD'); }} className="bg-white p-10 rounded-3xl shadow-sm border border-gray-100 hover:border-blue-500 hover:shadow-xl transition-all flex flex-col items-center group">
                            <div className="p-4 bg-blue-50 rounded-2xl mb-4 group-hover:scale-110 transition-transform">
                                <Package className="w-12 h-12 text-blue-600" />
                            </div>
                            <h3 className="text-2xl font-bold text-gray-900">Novo Pedido</h3>
                            <p className="text-gray-500 mt-2 text-center">Locação com baixa imediata no estoque</p>
                        </button>
                        <button onClick={() => { setOrderType('ORCAMENTO'); setCurrentStep('CART'); }} className="bg-white p-10 rounded-3xl shadow-sm border border-gray-100 hover:border-green-500 hover:shadow-xl transition-all flex flex-col items-center group">
                            <div className="p-4 bg-green-50 rounded-2xl mb-4 group-hover:scale-110 transition-transform">
                                <FileText className="w-12 h-12 text-green-600" />
                            </div>
                            <h3 className="text-2xl font-bold text-gray-900">Novo Orçamento</h3>
                            <p className="text-gray-500 mt-2 text-center">Cotação de preços sem reserva de estoque</p>
                        </button>
                    </div>
                )}

                {currentStep === 'SELECT_PERIOD' && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {['DIARIA', 'SEMANAL', 'QUINZENAL', 'MENSAL'].map((period) => (
                        <button key={period} onClick={() => { setBillingPeriod(period as any); setCurrentStep('CART'); }} className={`p-6 rounded-2xl border text-left transition-all ${billingPeriod === period ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/30 border-transparent' : 'bg-white hover:border-blue-300'}`}>
                            <span className="font-bold text-lg">{period}</span>
                        </button>
                    ))}
                </div>
                )}

                {currentStep === 'CART' && (
                    <div className="space-y-4">
                        <div className="relative mb-6">
                            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                            <input type="text" placeholder="Buscar equipamentos..." className="w-full pl-12 pr-4 py-4 bg-white border border-gray-200 rounded-2xl outline-none focus:ring-2 focus:ring-blue-500" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)}/>
                        </div>
                        {equipment.filter(e => e.name.toLowerCase().includes(searchTerm.toLowerCase())).map(item => {
                            const isInCart = cart.find(c => c.item.id === item.id);
                            const stock = getEquipmentStock(item.id);
                            const hasStock = stock.available > 0;
                            
                            return (
                                <div key={item.id} className={`bg-white p-4 rounded-2xl border ${isInCart ? 'border-blue-500 ring-1 ring-blue-500' : 'border-gray-100'} flex items-center justify-between transition-all`}>
                                    <div className="flex items-center gap-4">
                                        <img src={item.imageUrl} className="w-16 h-16 rounded-lg object-cover bg-gray-100" />
                                        <div>
                                            <h4 className="font-bold text-gray-900">{item.name}</h4>
                                            <div className="flex items-center text-sm gap-3 mt-1">
                                                <span className="text-gray-500">R$ {item.priceMonthly.toFixed(2)}/mês</span>
                                                {orderType === 'PEDIDO' && (
                                                    <span className={`text-xs font-bold px-2 py-0.5 rounded ${hasStock ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                                        {stock.available} disp
                                                    </span>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                    {isInCart ? (
                                        <div className="flex items-center gap-3 bg-gray-50 rounded-xl p-1">
                                            <button onClick={() => updateQuantity(item.id, -1)} className="p-2 hover:bg-white rounded-lg transition-colors"><Minus className="w-4 h-4 text-gray-600"/></button>
                                            <span className="font-bold w-6 text-center">{isInCart.quantity}</span>
                                            <button onClick={() => updateQuantity(item.id, 1)} className="p-2 hover:bg-white rounded-lg transition-colors"><Plus className="w-4 h-4 text-gray-600"/></button>
                                        </div>
                                    ) : (
                                        <button onClick={() => addToCart(item)} disabled={orderType === 'PEDIDO' && !hasStock} className="p-3 bg-blue-50 text-blue-600 rounded-xl hover:bg-blue-100 disabled:opacity-50 disabled:cursor-not-allowed">
                                            <Plus className="w-5 h-5"/>
                                        </button>
                                    )}
                                </div>
                            )
                        })}
                        {equipment.filter(e => e.name.toLowerCase().includes(searchTerm.toLowerCase())).length === 0 && (
                            <div className="text-center py-10 text-gray-400">Nenhum equipamento encontrado.</div>
                        )}
                    </div>
                )}

                {currentStep === 'DETAILS' && (
                <div className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="p-6 border-b border-gray-100 bg-gray-50/50">
                        <h3 className="font-bold text-gray-900">Dados da Contratação e Entrega</h3>
                    </div>
                    
                    <div className="p-8 space-y-8">
                        {/* Client Selection */}
                        <div>
                            <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block ml-1">Cliente</label>
                            {!newClientMode ? (
                                <div className="flex gap-2">
                                    <div className="relative flex-1">
                                        <select 
                                            className="w-full bg-gray-50 border border-gray-200 rounded-xl p-4 font-medium outline-none appearance-none focus:ring-2 focus:ring-blue-500"
                                            value={selectedClient}
                                            onChange={e => {
                                                setSelectedClient(e.target.value);
                                                const c = clients.find(cl => cl.id === e.target.value);
                                                if(c) {
                                                    setDeliveryAddress({
                                                        street: c.street, number: c.number, neighborhood: c.neighborhood,
                                                        city: c.city, state: c.state, zipCode: c.zipCode,
                                                        complement: c.complement, reference: c.reference
                                                    });
                                                }
                                            }}
                                        >
                                            <option value="">Selecione um cliente...</option>
                                            {clients.map(c => <option key={c.id} value={c.id}>{c.name} - {c.document}</option>)}
                                        </select>
                                        <ChevronRight className="absolute right-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400 pointer-events-none rotate-90" />
                                    </div>
                                    <button onClick={() => setNewClientMode(true)} className="px-5 bg-blue-50 text-blue-600 rounded-xl hover:bg-blue-100 transition-colors border border-blue-100 flex items-center gap-2 font-medium">
                                        <UserPlus className="w-5 h-5" /> Novo
                                    </button>
                                </div>
                            ) : (
                                <div className="bg-blue-50/50 p-6 rounded-2xl border border-blue-100 space-y-4 animate-slide-up">
                                    <div className="flex justify-between items-center mb-2"><h3 className="font-bold text-blue-800 flex items-center"><UserPlus className="w-4 h-4 mr-2"/> Novo Cadastro Rápido</h3><button onClick={() => setNewClientMode(false)} className="text-red-500 text-xs font-bold bg-white px-3 py-1.5 rounded-lg border border-red-100 hover:bg-red-50">Cancelar</button></div>
                                    <input placeholder="Nome / Razão Social" className="w-full p-3.5 bg-white border border-gray-200 rounded-xl outline-none focus:border-blue-500" value={newClientData.name} onChange={e => updateNewClient('name', e.target.value)} />
                                    <div className="grid grid-cols-2 gap-4">
                                        <input placeholder="CPF / CNPJ" className="w-full p-3.5 bg-white border border-gray-200 rounded-xl outline-none focus:border-blue-500" value={newClientData.document} onChange={e => updateNewClient('document', e.target.value)} />
                                        <input placeholder="Telefone" className="w-full p-3.5 bg-white border border-gray-200 rounded-xl outline-none focus:border-blue-500" value={newClientData.phone} onChange={e => updateNewClient('phone', e.target.value)} />
                                    </div>
                                    <input placeholder="Email" className="w-full p-3.5 bg-white border border-gray-200 rounded-xl outline-none focus:border-blue-500" value={newClientData.email} onChange={e => updateNewClient('email', e.target.value)} />
                                    <p className="text-xs text-blue-600">Endereço será preenchido abaixo.</p>
                                </div>
                            )}
                        </div>

                        {/* Extended Address Form */}
                        <div>
                            <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center"><MapPin className="w-4 h-4 mr-2 text-blue-600"/> Endereço de Entrega</h4>
                            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                                <div className="md:col-span-1">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">CEP</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.zipCode} onChange={e => {updateAddress('zipCode', e.target.value); if(newClientMode) updateNewClient('zipCode', e.target.value)}} placeholder="00000-000" />
                                </div>
                                <div className="md:col-span-3">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Rua / Logradouro</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.street} onChange={e => {updateAddress('street', e.target.value); if(newClientMode) updateNewClient('street', e.target.value)}} placeholder="Av. Principal" />
                                </div>
                                <div className="md:col-span-1">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Número</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.number} onChange={e => {updateAddress('number', e.target.value); if(newClientMode) updateNewClient('number', e.target.value)}} placeholder="123" />
                                </div>
                                <div className="md:col-span-3">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Complemento</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.complement} onChange={e => {updateAddress('complement', e.target.value); if(newClientMode) updateNewClient('complement', e.target.value)}} placeholder="Apto 101, Galpão B" />
                                </div>
                                <div className="md:col-span-2">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Bairro</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.neighborhood} onChange={e => {updateAddress('neighborhood', e.target.value); if(newClientMode) updateNewClient('neighborhood', e.target.value)}} placeholder="Centro" />
                                </div>
                                <div className="md:col-span-1">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Cidade</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.city} onChange={e => {updateAddress('city', e.target.value); if(newClientMode) updateNewClient('city', e.target.value)}} placeholder="Maceió" />
                                </div>
                                <div className="md:col-span-1">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Estado</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.state} onChange={e => {updateAddress('state', e.target.value); if(newClientMode) updateNewClient('state', e.target.value)}} placeholder="AL" />
                                </div>
                                <div className="md:col-span-4">
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-wider ml-1">Ponto de Referência</label>
                                    <input className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={deliveryAddress.reference} onChange={e => {updateAddress('reference', e.target.value); if(newClientMode) updateNewClient('reference', e.target.value)}} placeholder="Próximo ao mercado..." />
                                </div>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6 border-t border-gray-100">
                            <div className="space-y-4">
                                <div>
                                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block ml-1">Forma de Pagamento</label>
                                    <div className="grid grid-cols-2 gap-2">
                                        {['PIX', 'CARTAO', 'DINHEIRO', 'BOLETO'].map(method => (
                                            <button 
                                                key={method}
                                                onClick={() => setPaymentMethod(method as any)}
                                                className={`p-3 rounded-xl border text-sm font-bold transition-all ${paymentMethod === method ? 'bg-blue-600 text-white border-transparent' : 'bg-gray-50 border-gray-200 text-gray-600 hover:bg-white'}`}
                                            >
                                                {method === 'CARTAO' ? 'CARTÃO' : method}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                                <div>
                                    <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block ml-1">Frete (R$)</label>
                                    <input type="number" className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" value={shippingCost} onChange={(e) => setShippingCost(parseFloat(e.target.value) || 0)} />
                                </div>
                            </div>
                            <div>
                                <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2 block ml-1">Observações Gerais</label>
                                <textarea className="w-full p-3.5 bg-gray-50 border border-gray-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500 h-[140px]" value={observations} onChange={(e) => setObservations(e.target.value)} placeholder="Instruções adicionais..." />
                            </div>
                        </div>
                    </div>
                </div>
            )}

            </div>

            {/* Sidebar Summary */}
            <div className="lg:col-span-1">
                <div className="bg-white p-6 rounded-3xl shadow-xl shadow-gray-200/50 border border-gray-100 sticky top-24">
                    <h3 className="text-lg font-bold text-gray-900 mb-6 flex items-center">
                        <ShoppingCart className="w-5 h-5 mr-3 text-blue-600" /> Resumo
                    </h3>
                    {cart.length === 0 ? (
                        <div className="text-center py-8 text-gray-400 text-sm">Seu carrinho está vazio.</div>
                    ) : (
                        <div className="space-y-4 max-h-[300px] overflow-y-auto mb-6 custom-scrollbar pr-2">
                            {cart.map((c) => (
                                <div key={c.item.id} className="flex justify-between items-start text-sm pb-4 border-b border-gray-50">
                                    <div className="flex-1 pr-3"><p className="font-semibold text-gray-900">{c.item.name}</p><p className="text-xs text-gray-400">{c.quantity}x</p></div>
                                    <div className="text-right"><p className="font-bold text-gray-900">R$ {(c.quantity * (billingPeriod === 'MENSAL' ? c.item.priceMonthly : c.item.priceWeekly)).toFixed(2)}</p><button onClick={() => removeFromCart(c.item.id)} className="text-red-400 text-xs hover:text-red-600">Remover</button></div>
                                </div>
                            ))}
                        </div>
                    )}
                    
                    {cart.length > 0 && orderType === 'PEDIDO' && (
                        <div className="bg-gray-50 rounded-2xl p-4 space-y-2 mb-6">
                            <div className="flex justify-between text-sm text-gray-500"><span>Subtotal</span><span>R$ {calculateTotalForPeriod(billingPeriod).toFixed(2)}</span></div>
                            <div className="flex justify-between text-sm text-gray-500"><span>Frete</span><span>R$ {shippingCost.toFixed(2)}</span></div>
                            <div className="border-t border-gray-200 my-2 pt-2 flex justify-between font-bold text-lg text-gray-900"><span>Total</span><span className="text-blue-600">R$ {currentTotal.toFixed(2)}</span></div>
                        </div>
                    )}
                    
                    {/* Navigation Buttons */}
                    <div className="space-y-3">
                        {currentStep === 'CART' && <button onClick={() => setCurrentStep('DETAILS')} disabled={cart.length === 0} className="w-full py-4 bg-blue-600 text-white rounded-2xl font-bold hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed">Ir para Dados</button>}
                        {currentStep === 'DETAILS' && <button onClick={handleFinishOrder} className="w-full py-4 bg-emerald-600 text-white rounded-2xl font-bold hover:bg-emerald-700 transition-colors shadow-lg shadow-emerald-500/20 active:scale-95">Confirmar e Finalizar</button>}
                    </div>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

export default NewOrder;
